#UAC_IIND4417 - Minería de Datos

### Otoño 2023

### IIND4417_Lab-1.3

**Enrique Naredo García**

<font size = 2>
©️ Todos los derechos reservados. All rights reserved.

*Nota: El presente documento es una herramienta diseñada única y exclusivamente para los estudiantes de la asignatura arriba mencionada. Queda prohibido compartir este documento con cualquier otra persona, aún siendo de la misma clase, grupo o de la Universidad sin consentimiento del autor. Queda prohibida la reproducción total o parcial de este documento por cualquier medio o procedimiento, ya sea electrónico o mecánico, el tratamiento informático, el alquiler o cualquier otra forma de cesión sin la autorización previa y por escrito del autor.*
</font>

#Limpieza de datos

La limpieza de datos significa corregir datos. Los datos incorrectos podrían ser:

* Celdas vacías.
* Datos en formato incorrecto.
* Información incorrecta.
* Duplicados.

In [1]:
import pandas as pd

In [39]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/calories.csv')
df.head()

   Numero  Duration         Date  Pulse  Maxpulse  Calories
0       0      60.0  2020/12/01'  110.0     130.0     409.1
1       1      60.0  2020/12/02'  117.0     145.0     479.0
2       2      60.0  2020/12/03'  103.0     135.0     340.0
3       3      45.0  2020/12/04'  109.0     175.0     282.4
4       4      45.0  2020/12/05'  117.0     148.0     406.0

In [43]:
df.tail()

    Numero  Duration         Date  Pulse  Maxpulse  Calories
27      27      60.0  2020/12/27'   92.0     118.0     241.0
28      28      60.0  2020/12/28'  103.0     132.0       NaN
29      29      60.0  2020/12/29'  100.0     132.0     280.0
30      30      60.0  2020/12/30'  102.0     129.0     380.3
31      31      60.0  2020/12/31'   92.0     115.0     243.0

In [40]:
print("Número total de registros: ", len(df.index),"\n")
print(df.to_string())

Número total de registros:  32

    Numero  Duration         Date  Pulse  Maxpulse  Calories
0        0      60.0  2020/12/01'  110.0     130.0     409.1
1        1      60.0  2020/12/02'  117.0     145.0     479.0
2        2      60.0  2020/12/03'  103.0     135.0     340.0
3        3      45.0  2020/12/04'  109.0     175.0     282.4
4        4      45.0  2020/12/05'  117.0     148.0     406.0
5        5      60.0  2020/12/06'  102.0     127.0     300.0
6        6      60.0  2020/12/07'  110.0     136.0     374.0
7        7     450.0  2020/12/08'  104.0     134.0     253.3
8        8      30.0  2020/12/09'  109.0     133.0     195.1
9        9      60.0  2020/12/10'   98.0     124.0     269.0
10      10      60.0  2020/12/11'  103.0     147.0     329.3
11      11      60.0  2020/12/12'  100.0     120.0     250.7
12      12      60.0  2020/12/12'  100.0     120.0     250.7
13      13      60.0  2020/12/13'  106.0     128.0     345.3
14      14      60.0  2020/12/14'  104.0     132.0     379.3
15      15      60.0  2020/12/15'   98.0     123.0     275.0
16      16      60.0  2020/12/16'   98.0     120.0     215.2
17      17      60.0  2020/12/17'  100.0     120.0     300.0
18      18      45.0  2020/12/18'   90.0     112.0       NaN
19      19      60.0  2020/12/19'  103.0     123.0     323.0
20      20      45.0  2020/12/20'   97.0     125.0     243.0
21      21      60.0  2020/12/21'  108.0     131.0     364.2
22      22      45.0          NaN  100.0     119.0     282.0
23      23      60.0  2020/12/23'  130.0     101.0     300.0
24      24      45.0  2020/12/24'  105.0     132.0     246.0
25      25      60.0  2020/12/25'  102.0     126.0     334.5
26      26      60.0   26/12/2020  100.0     120.0     250.0
27      27      60.0  2020/12/27'   92.0     118.0     241.0
28      28      60.0  2020/12/28'  103.0     132.0       NaN
29      29      60.0  2020/12/29'  100.0     132.0     280.0
30      30      60.0  2020/12/30'  102.0     129.0     380.3
31      31      60.0  2020/12/31'   92.0     115.0     243.0

## Eliminar filas
Eliminar todas las filas con valores NULL.

In [44]:
# copia el data frame
df2 = df.copy()
df2.dropna(inplace = True)

print("Número total de registros: ", len(df2.index),"\n")
print(df2.to_string())

Número total de registros:  29

    Numero  Duration         Date  Pulse  Maxpulse  Calories
0        0      60.0  2020/12/01'  110.0     130.0     409.1
1        1      60.0  2020/12/02'  117.0     145.0     479.0
2        2      60.0  2020/12/03'  103.0     135.0     340.0
3        3      45.0  2020/12/04'  109.0     175.0     282.4
4        4      45.0  2020/12/05'  117.0     148.0     406.0
5        5      60.0  2020/12/06'  102.0     127.0     300.0
6        6      60.0  2020/12/07'  110.0     136.0     374.0
7        7     450.0  2020/12/08'  104.0     134.0     253.3
8        8      30.0  2020/12/09'  109.0     133.0     195.1
9        9      60.0  2020/12/10'   98.0     124.0     269.0
10      10      60.0  2020/12/11'  103.0     147.0     329.3
11      11      60.0  2020/12/12'  100.0     120.0     250.7
12      12      60.0  2020/12/12'  100.0     120.0     250.7
13      13      60.0  2020/12/13'  106.0     128.0     345.3
14      14      60.0  2020/12/14'  104.0     132.0     379.3
15      15      60.0  2020/12/15'   98.0     123.0     275.0
16      16      60.0  2020/12/16'   98.0     120.0     215.2
17      17      60.0  2020/12/17'  100.0     120.0     300.0
19      19      60.0  2020/12/19'  103.0     123.0     323.0
20      20      45.0  2020/12/20'   97.0     125.0     243.0
21      21      60.0  2020/12/21'  108.0     131.0     364.2
23      23      60.0  2020/12/23'  130.0     101.0     300.0
24      24      45.0  2020/12/24'  105.0     132.0     246.0
25      25      60.0  2020/12/25'  102.0     126.0     334.5
26      26      60.0   26/12/2020  100.0     120.0     250.0
27      27      60.0  2020/12/27'   92.0     118.0     241.0
29      29      60.0  2020/12/29'  100.0     132.0     280.0
30      30      60.0  2020/12/30'  102.0     129.0     380.3
31      31      60.0  2020/12/31'   92.0     115.0     243.0

##Reemplazar valores vacíos

Otra forma de tratar con celdas vacías es insertar un nuevo valor.

* De esta manera, no tendrá que eliminar filas enteras solo por tener algunas celdas vacías.

* El método ```fillna()``` nos permite reemplazar celdas vacías con un valor.

In [47]:
# copia el data frame
df3 = df.copy()
df3.fillna(12500, inplace = True)

print("Número total de registros: ", len(df3.index),"\n")
print(df3.to_string())

Número total de registros:  32

    Numero  Duration         Date  Pulse  Maxpulse  Calories
0        0      60.0  2020/12/01'  110.0     130.0     409.1
1        1      60.0  2020/12/02'  117.0     145.0     479.0
2        2      60.0  2020/12/03'  103.0     135.0     340.0
3        3      45.0  2020/12/04'  109.0     175.0     282.4
4        4      45.0  2020/12/05'  117.0     148.0     406.0
5        5      60.0  2020/12/06'  102.0     127.0     300.0
6        6      60.0  2020/12/07'  110.0     136.0     374.0
7        7     450.0  2020/12/08'  104.0     134.0     253.3
8        8      30.0  2020/12/09'  109.0     133.0     195.1
9        9      60.0  2020/12/10'   98.0     124.0     269.0
10      10      60.0  2020/12/11'  103.0     147.0     329.3
11      11      60.0  2020/12/12'  100.0     120.0     250.7
12      12      60.0  2020/12/12'  100.0     120.0     250.7
13      13      60.0  2020/12/13'  106.0     128.0     345.3
14      14      60.0  2020/12/14'  104.0     132.0     379.3
15      15      60.0  2020/12/15'   98.0     123.0     275.0
16      16      60.0  2020/12/16'   98.0     120.0     215.2
17      17      60.0  2020/12/17'  100.0     120.0     300.0
18      18      45.0  2020/12/18'   90.0     112.0   12500.0
19      19      60.0  2020/12/19'  103.0     123.0     323.0
20      20      45.0  2020/12/20'   97.0     125.0     243.0
21      21      60.0  2020/12/21'  108.0     131.0     364.2
22      22      45.0        12500  100.0     119.0     282.0
23      23      60.0  2020/12/23'  130.0     101.0     300.0
24      24      45.0  2020/12/24'  105.0     132.0     246.0
25      25      60.0  2020/12/25'  102.0     126.0     334.5
26      26      60.0   26/12/2020  100.0     120.0     250.0
27      27      60.0  2020/12/27'   92.0     118.0     241.0
28      28      60.0  2020/12/28'  103.0     132.0   12500.0
29      29      60.0  2020/12/29'  100.0     132.0     280.0
30      30      60.0  2020/12/30'  102.0     129.0     380.3
31      31      60.0  2020/12/31'   92.0     115.0     243.0

##Reemplazar solo columnas especificadas

El ejemplo anterior reemplaza todas las celdas vacías en todo el marco de datos.

* Para reemplazar solo valores vacíos en una columna.
* Se debe especificar el nombre de la columna.

In [49]:
# copia el data frame
df4 = df.copy()
df4["Calories"].fillna(18000, inplace = True)

print("Número total de registros: ", len(df4.index),"\n")
print(df4.to_string())

# no se remplazo el NaN en Date del registro 22

Número total de registros:  32

    Numero  Duration         Date  Pulse  Maxpulse  Calories
0        0      60.0  2020/12/01'  110.0     130.0     409.1
1        1      60.0  2020/12/02'  117.0     145.0     479.0
2        2      60.0  2020/12/03'  103.0     135.0     340.0
3        3      45.0  2020/12/04'  109.0     175.0     282.4
4        4      45.0  2020/12/05'  117.0     148.0     406.0
5        5      60.0  2020/12/06'  102.0     127.0     300.0
6        6      60.0  2020/12/07'  110.0     136.0     374.0
7        7     450.0  2020/12/08'  104.0     134.0     253.3
8        8      30.0  2020/12/09'  109.0     133.0     195.1
9        9      60.0  2020/12/10'   98.0     124.0     269.0
10      10      60.0  2020/12/11'  103.0     147.0     329.3
11      11      60.0  2020/12/12'  100.0     120.0     250.7
12      12      60.0  2020/12/12'  100.0     120.0     250.7
13      13      60.0  2020/12/13'  106.0     128.0     345.3
14      14      60.0  2020/12/14'  104.0     132.0     379.3
15      15      60.0  2020/12/15'   98.0     123.0     275.0
16      16      60.0  2020/12/16'   98.0     120.0     215.2
17      17      60.0  2020/12/17'  100.0     120.0     300.0
18      18      45.0  2020/12/18'   90.0     112.0   18000.0
19      19      60.0  2020/12/19'  103.0     123.0     323.0
20      20      45.0  2020/12/20'   97.0     125.0     243.0
21      21      60.0  2020/12/21'  108.0     131.0     364.2
22      22      45.0          NaN  100.0     119.0     282.0
23      23      60.0  2020/12/23'  130.0     101.0     300.0
24      24      45.0  2020/12/24'  105.0     132.0     246.0
25      25      60.0  2020/12/25'  102.0     126.0     334.5
26      26      60.0   26/12/2020  100.0     120.0     250.0
27      27      60.0  2020/12/27'   92.0     118.0     241.0
28      28      60.0  2020/12/28'  103.0     132.0   18000.0
29      29      60.0  2020/12/29'  100.0     132.0     280.0
30      30      60.0  2020/12/30'  102.0     129.0     380.3
31      31      60.0  2020/12/31'   92.0     115.0     243.0

##Reemplazar usando media, mediana o moda

* Una forma común de reemplazar celdas vacías es calcular el valor medio, mediano o moda de la columna.

* Pandas utiliza los métodos ```mean()```, ```mediana()```, y ```mode()``` para calcular los valores respectivos para una columna específica.

In [53]:
# copia el data frame
df5 = df.copy()

mediaCalorias = df5["Calories"].mean()
df5["Calories"].fillna(mediaCalorias, inplace = True)

print("Número total de registros: ", len(df5.index),"\n")
print(df5.to_string())

# no se puede extraer la media de Date por ser cadena de caracteres

Número total de registros:  32

    Numero  Duration         Date  Pulse  Maxpulse  Calories
0        0      60.0  2020/12/01'  110.0     130.0    409.10
1        1      60.0  2020/12/02'  117.0     145.0    479.00
2        2      60.0  2020/12/03'  103.0     135.0    340.00
3        3      45.0  2020/12/04'  109.0     175.0    282.40
4        4      45.0  2020/12/05'  117.0     148.0    406.00
5        5      60.0  2020/12/06'  102.0     127.0    300.00
6        6      60.0  2020/12/07'  110.0     136.0    374.00
7        7     450.0  2020/12/08'  104.0     134.0    253.30
8        8      30.0  2020/12/09'  109.0     133.0    195.10
9        9      60.0  2020/12/10'   98.0     124.0    269.00
10      10      60.0  2020/12/11'  103.0     147.0    329.30
11      11      60.0  2020/12/12'  100.0     120.0    250.70
12      12      60.0  2020/12/12'  100.0     120.0    250.70
13      13      60.0  2020/12/13'  106.0     128.0    345.30
14      14      60.0  2020/12/14'  104.0     132.0    379.30
15      15      60.0  2020/12/15'   98.0     123.0    275.00
16      16      60.0  2020/12/16'   98.0     120.0    215.20
17      17      60.0  2020/12/17'  100.0     120.0    300.00
18      18      45.0  2020/12/18'   90.0     112.0    304.68
19      19      60.0  2020/12/19'  103.0     123.0    323.00
20      20      45.0  2020/12/20'   97.0     125.0    243.00
21      21      60.0  2020/12/21'  108.0     131.0    364.20
22      22      45.0          NaN  100.0     119.0    282.00
23      23      60.0  2020/12/23'  130.0     101.0    300.00
24      24      45.0  2020/12/24'  105.0     132.0    246.00
25      25      60.0  2020/12/25'  102.0     126.0    334.50
26      26      60.0   26/12/2020  100.0     120.0    250.00
27      27      60.0  2020/12/27'   92.0     118.0    241.00
28      28      60.0  2020/12/28'  103.0     132.0    304.68
29      29      60.0  2020/12/29'  100.0     132.0    280.00
30      30      60.0  2020/12/30'  102.0     129.0    380.30
31      31      60.0  2020/12/31'   92.0     115.0    243.00

In [54]:
# copia el data frame
df6 = df.copy()

medianaCalorias = df6["Calories"].median()
df6["Calories"].fillna(medianaCalorias, inplace = True)

print("Número total de registros: ", len(df6.index),"\n")
print(df6.to_string())

# noten como el valor de la mediana es diferente que el de la media

Número total de registros:  32

    Numero  Duration         Date  Pulse  Maxpulse  Calories
0        0      60.0  2020/12/01'  110.0     130.0     409.1
1        1      60.0  2020/12/02'  117.0     145.0     479.0
2        2      60.0  2020/12/03'  103.0     135.0     340.0
3        3      45.0  2020/12/04'  109.0     175.0     282.4
4        4      45.0  2020/12/05'  117.0     148.0     406.0
5        5      60.0  2020/12/06'  102.0     127.0     300.0
6        6      60.0  2020/12/07'  110.0     136.0     374.0
7        7     450.0  2020/12/08'  104.0     134.0     253.3
8        8      30.0  2020/12/09'  109.0     133.0     195.1
9        9      60.0  2020/12/10'   98.0     124.0     269.0
10      10      60.0  2020/12/11'  103.0     147.0     329.3
11      11      60.0  2020/12/12'  100.0     120.0     250.7
12      12      60.0  2020/12/12'  100.0     120.0     250.7
13      13      60.0  2020/12/13'  106.0     128.0     345.3
14      14      60.0  2020/12/14'  104.0     132.0     379.3
15      15      60.0  2020/12/15'   98.0     123.0     275.0
16      16      60.0  2020/12/16'   98.0     120.0     215.2
17      17      60.0  2020/12/17'  100.0     120.0     300.0
18      18      45.0  2020/12/18'   90.0     112.0     291.2
19      19      60.0  2020/12/19'  103.0     123.0     323.0
20      20      45.0  2020/12/20'   97.0     125.0     243.0
21      21      60.0  2020/12/21'  108.0     131.0     364.2
22      22      45.0          NaN  100.0     119.0     282.0
23      23      60.0  2020/12/23'  130.0     101.0     300.0
24      24      45.0  2020/12/24'  105.0     132.0     246.0
25      25      60.0  2020/12/25'  102.0     126.0     334.5
26      26      60.0   26/12/2020  100.0     120.0     250.0
27      27      60.0  2020/12/27'   92.0     118.0     241.0
28      28      60.0  2020/12/28'  103.0     132.0     291.2
29      29      60.0  2020/12/29'  100.0     132.0     280.0
30      30      60.0  2020/12/30'  102.0     129.0     380.3
31      31      60.0  2020/12/31'   92.0     115.0     243.0

In [56]:
# copia el data frame
df7 = df.copy()

medianaCalorias = df7["Calories"].mode()[0]
df7["Calories"].fillna(medianaCalorias, inplace = True)

print("Número total de registros: ", len(df7.index),"\n")
print(df7.to_string())

Número total de registros:  32

    Numero  Duration         Date  Pulse  Maxpulse  Calories
0        0      60.0  2020/12/01'  110.0     130.0     409.1
1        1      60.0  2020/12/02'  117.0     145.0     479.0
2        2      60.0  2020/12/03'  103.0     135.0     340.0
3        3      45.0  2020/12/04'  109.0     175.0     282.4
4        4      45.0  2020/12/05'  117.0     148.0     406.0
5        5      60.0  2020/12/06'  102.0     127.0     300.0
6        6      60.0  2020/12/07'  110.0     136.0     374.0
7        7     450.0  2020/12/08'  104.0     134.0     253.3
8        8      30.0  2020/12/09'  109.0     133.0     195.1
9        9      60.0  2020/12/10'   98.0     124.0     269.0
10      10      60.0  2020/12/11'  103.0     147.0     329.3
11      11      60.0  2020/12/12'  100.0     120.0     250.7
12      12      60.0  2020/12/12'  100.0     120.0     250.7
13      13      60.0  2020/12/13'  106.0     128.0     345.3
14      14      60.0  2020/12/14'  104.0     132.0     379.3
15      15      60.0  2020/12/15'   98.0     123.0     275.0
16      16      60.0  2020/12/16'   98.0     120.0     215.2
17      17      60.0  2020/12/17'  100.0     120.0     300.0
18      18      45.0  2020/12/18'   90.0     112.0     300.0
19      19      60.0  2020/12/19'  103.0     123.0     323.0
20      20      45.0  2020/12/20'   97.0     125.0     243.0
21      21      60.0  2020/12/21'  108.0     131.0     364.2
22      22      45.0          NaN  100.0     119.0     282.0
23      23      60.0  2020/12/23'  130.0     101.0     300.0
24      24      45.0  2020/12/24'  105.0     132.0     246.0
25      25      60.0  2020/12/25'  102.0     126.0     334.5
26      26      60.0   26/12/2020  100.0     120.0     250.0
27      27      60.0  2020/12/27'   92.0     118.0     241.0
28      28      60.0  2020/12/28'  103.0     132.0     300.0
29      29      60.0  2020/12/29'  100.0     132.0     280.0
30      30      60.0  2020/12/30'  102.0     129.0     380.3
31      31      60.0  2020/12/31'   92.0     115.0     243.0